-- AlterTable
ALTER TABLE "User" ADD COLUMN     "balance" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN     "coinsPerTap" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "energy" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN     "energyMax" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN     "energyPerSecond" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "energyUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
